import bodyHourGlassImage from "../assets/images/png/bodyHourGlass.png";
import bodyOvalImage from "../assets/images/png/bodyOval.png";
import bodyTriangleImage from "../assets/images/png/bodyTriangle.png";
import bodyRectangularImage from "../assets/images/png/bodyRectangular.png";
import bodyInverseTriangleImage from "../assets/images/png/bodyInverseTriangle.png";
import bodyDefaultImage from "../assets/images/png/bodyDefault.png";

export const genders = [
  { id: "male", name: "Masculino" },
  { id: "female", name: "Feminino" },
  { id: "prefer_not_to_say", name: "Prefiro não dizer" },
  { id: "other", name: "Outro" },
];

export const clothesSize = [
  { id: "XXS-32", value: "32", label: "XXS" },
  { id: "XS-34", value: "34", label: "XS" },
  { id: "P-36", value: "36", label: "P" },
  { id: "P-38", value: "38", label: "P/M" },
  { id: "M-40", value: "40", label: "M" },
  { id: "M-42", value: "42", label: "M/G" },
  { id: "G-44", value: "44", label: "G" },
  { id: "GG-46", value: "46", label: "GG" },
  { id: "XGG-48", value: "48", label: "XGG" },
  { id: "XXG-50", value: "50", label: "XXG" },
];

export const jobRoles = [
  { value: "lawyer", label: "Advogado" },
  { value: "administrator", label: "Administrador" },
  { value: "agronomist", label: "Agrônomo" },
  { value: "systems-analyst", label: "Analista de Sistemas" },
  { value: "archaeologist", label: "Arqueólogo" },
  { value: "architect", label: "Arquiteto" },
  { value: "plastic-artist", label: "Artista Plástico" },
  { value: "social-worker", label: "Assistente Social" },
  { value: "astronomer", label: "Astrônomo" },
  { value: "actor", label: "Ator" },
  { value: "auditor", label: "Auditor" },
  { value: "banker", label: "Bancário" },
  { value: "barber", label: "Barbeiro" },
  { value: "bartender", label: "Barman" },
  { value: "biologist", label: "Biólogo" },
  { value: "firefighter", label: "Bombeiro" },
  { value: "hairdresser", label: "Cabeleireiro" },
  { value: "singer", label: "Cantor" },
  { value: "carpenter", label: "Carpinteiro" },
  { value: "mailman", label: "Carteiro" },
  { value: "chef", label: "Chefe de Cozinha" },
  { value: "computer-scientist", label: "Cientista da Computação" },
  { value: "accountant", label: "Contador" },
  { value: "choreographer", label: "Coreógrafo" },
  { value: "cook", label: "Cozinheiro" },
  { value: "dancer", label: "Dançarino" },
  { value: "dentist", label: "Dentista" },
  { value: "interior-designer", label: "Designer de Interiores" },
  { value: "graphic-designer", label: "Designer Gráfico" },
  { value: "economist", label: "Economista" },
  { value: "video-editor", label: "Editor de Vídeo" },
  { value: "electrician", label: "Eletricista" },
  { value: "plumber", label: "Encanador" },
  { value: "civil-engineer", label: "Engenheiro Civil" },
  { value: "software-engineer", label: "Engenheiro de Software" },
  { value: "mechanical-engineer", label: "Engenheiro Mecânico" },
  { value: "nurse", label: "Enfermeiro" },
  { value: "fashion-designer", label: "Estilista" },
  { value: "pharmacist", label: "Farmacêutico" },
  { value: "physicist", label: "Físico" },
  { value: "physiotherapist", label: "Fisioterapeuta" },
  { value: "photographer", label: "Fotógrafo" },
  { value: "waiter", label: "Garçom" },
  { value: "geologist", label: "Geólogo" },
  { value: "environmental-manager", label: "Gestor Ambiental" },
  { value: "historian", label: "Historiador" },
  { value: "journalist", label: "Jornalista" },
  { value: "judge", label: "Juiz" },
  { value: "sign-language-interpreter", label: "Libras Intérprete" },
  { value: "mechanic", label: "Mecânico" },
  { value: "cardiologist", label: "Médico Cardiologista" },
  { value: "general-practitioner", label: "Médico Clínico Geral" },
  { value: "pediatrician", label: "Médico Pediatra" },
  { value: "driver", label: "Motorista" },
  { value: "nutritionist", label: "Nutricionista" },
  { value: "machine-operator", label: "Operador de Máquinas" },
  { value: "baker", label: "Padeiro" },
  { value: "educator", label: "Pedagogo" },
  { value: "construction-worker", label: "Pedreiro" },
  { value: "pilot", label: "Piloto de Avião" },
  { value: "military-police", label: "Policial Militar" },
  { value: "civil-police", label: "Policial Civil" },
  { value: "event-producer", label: "Produtor de Eventos" },
  { value: "math-teacher", label: "Professor de Matemática" },
  { value: "psychologist", label: "Psicólogo" },
  { value: "advertiser", label: "Publicitário" },
  { value: "chemist", label: "Químico" },
  { value: "receptionist", label: "Recepcionista" },
  { value: "copywriter", label: "Redator" },
  { value: "screenwriter", label: "Roteirista" },
  { value: "welder", label: "Soldador" },
  { value: "it-technician", label: "Técnico de Informática" },
  { value: "translator", label: "Tradutor" },
  { value: "tourism-specialist", label: "Turismólogo" },
  { value: "veterinarian", label: "Veterinário" },
  { value: "web-designer", label: "Web Designer" },
  { value: "zoologist", label: "Zootecnista" },
];

export const bodyTypes = [
  {
    id: "hourglass-body",
    label: "Corpo Ampulheta",
    image: bodyHourGlassImage,
    custom: false,
  },
  {
    id: "oval-body",
    label: "Corpo Oval",
    image: bodyOvalImage,
    custom: false,
  },
  {
    id: "triangle-body",
    label: "Corpo Triângulo",
    image: bodyTriangleImage,
    custom: false,
  },
  {
    id: "rectangular-body",
    label: "Corpo Retangular",
    image: bodyRectangularImage,
    custom: false,
  },
  {
    id: "inverse-triangle-body",
    label: "Corpo Triângulo Invertido",
    image: bodyInverseTriangleImage,
    custom: false,
  },
  {
    id: "default-body",
    label: "Inserir medidas manualmente",
    image: bodyDefaultImage,
    custom: true,
  },
];
